### PR TITLE
fix: remove artifact-registry

### PR DESCRIPTION
**Pull request by artemrys**
This PR removes `artifact-registry` step from the pipeline as we don't need Docker containers with add-on builds in the ghcr.io. It is not used in the infra anywhere. Also clean up README.md.

Test run: https://github.com/splunk/splunk-add-on-for-mysql/actions/runs/7669490177

### CODE REVIEW

**Comment by artemrys** [comment]
> I think in existing @ajanus-splunk compatibility pipeline TA build is being downloaded from artifacts related with given workflow execution. Worth confirming and taking under consideration when designing new solution

I don't think we are breaking this contract, `artifact-registry` uploads to GitHub Registry, not as workflow's artifact.

**Comment by kdoroszko-splunk** [comment]
I think we could also remove `images/artifacts_all.png` file and `images/modinput/` directory.

**Comment by artemrys** [comment]
> I think we could also remove `images/artifacts_all.png` file and `images/modinput/` directory. 

Let's do!

**Review by mbruzda-splunk — APPROVED** [review]

**Review by kdoroszko-splunk — APPROVED** [review]

**Pull request merged**
