### PR TITLE
fix: downgrade dorny/test-reporter to v1.7.0 and bump unreleased Python version

### PR DESCRIPTION
**Pull request by mkolasinski-splunk**
- Downgrade dorny/test-reporter action to `v1.7.0` as `v1.8.0` relies on node20 which is not supported in currently used `workflow-engine-base:2.0.3`

- Bump version of unreleased splunk with python3.9 to latest available build.

Tested here:
https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/7693652729/job/20963434508

This PR will be followed by backporting of same changes to `reusable-build-test-release v4.6`

### CODE REVIEW

**Comment by mkolasinski-splunk** [comment]
> Did you run a test to see if it actually works?

Attached test workflow execution

**Comment by kdoroszko-splunk** [comment]
> * Downgrade dorny/test-reporter action to `v1.7.0` as `v1.8.0` relies on node20 which is not supported in currently used `workflow-engine-base:2.0.3`
> * Bump version of unreleased splunk with python3.9 to latest available build.
> 
> Tested here: https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/7693652729/job/20963434508
> 
> This PR will be followed by backporting of same changes to `reusable-build-test-release v4.6`

Are we sure `reusable-build-test-release v4.6` not `reusable-build-test-release v4.1.6` ?

**Comment by mkolasinski-splunk** [comment]
> > * Downgrade dorny/test-reporter action to `v1.7.0` as `v1.8.0` relies on node20 which is not supported in currently used `workflow-engine-base:2.0.3`
> > * Bump version of unreleased splunk with python3.9 to latest available build.
> > 
> > Tested here: https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/7693652729/job/20963434508
> > This PR will be followed by backporting of same changes to `reusable-build-test-release v4.6`
> 
> Are we sure `reusable-build-test-release v4.6` not `reusable-build-test-release v4.1.6` ?

As in template dashboard most of the TAs are either on v2.12 or v2.6.1 template version, changes should be included in reusable-workflow v4.15 and v4.6.

Why do you propose v4.1.6?

**Comment by kdoroszko-splunk** [comment]
> > > * Downgrade dorny/test-reporter action to `v1.7.0` as `v1.8.0` relies on node20 which is not supported in currently used `workflow-engine-base:2.0.3`
> > > * Bump version of unreleased splunk with python3.9 to latest available build.
> > > 
> > > Tested here: https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/7693652729/job/20963434508
> > > This PR will be followed by backporting of same changes to `reusable-build-test-release v4.6`
> > 
> > 
> > Are we sure `reusable-build-test-release v4.6` not `reusable-build-test-release v4.1.6` ?
> 
> As in template dashboard most of the TAs are either on v2.12 or v2.6.1 template version, fix should be included in reusable-workflow v4.15 and v4.6.
> 
> Why do you propose v4.1.6?

Right, I confused the versions :)

**Review by kdoroszko-splunk — APPROVED** [review]

**Pull request merged**
