### PR TITLE
fix: update AppInspect CLI action to v2.5 #247

### PR DESCRIPTION
**Pull request by pbajaj-crest**
[https://github.com/splunk/appinspect-cli-action/releases/tag/v2.5.0](url)
[https://dev.splunk.com/enterprise/docs/relnotes/relnotes-appinspectcli/whatsnew/#v3502024-03-27](url)
[https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/8464669953](url)

### CODE REVIEW

**Comment by pbajaj-crest** [comment]
I have read the CLA Document and I hereby accept the CLA

**Comment by harshilgajera-crest** [comment]
I have read the CLA Document and I hereby accept the CLA

**Comment by harshilgajera-crest** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Comment by pbajaj-crest** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Review by kdoroszko-splunk — APPROVED** [review]

**Pull request merged**
